import torch
import torch.nn as nn
import math

class CarnotMobiusLedger(nn.Module):
    """
    Computes the Carnot-Möbius Efficiency Limit for the Gyroidic Stack.
    Incorporates the topological friction generated by the ADMR solver's phase mismatch,
    and calculates thermal runaway.
    """
    def __init__(self, xi_shear: float = 0.1, p_cool_max: float = 1000.0, p_nuclear: float = 2000.0):
        super().__init__()
        self.xi_shear = xi_shear
        self.p_cool_max = p_cool_max
        self.p_nuclear = p_nuclear
        
    def forward(self, 
                lambda_vac: torch.Tensor, 
                lambda_pump: torch.Tensor, 
                admr_residues: torch.Tensor,
                depth_N: int) -> dict:
        """
        Calculates the stack efficiency and flags thermal runaway.
        
        Args:
            lambda_vac: Base vacuum spectral density (Cold Sink)
            lambda_pump: Pumped highly excited state (Hot Reservoir)
            admr_residues: The phase mismatches (nabla epsilon_n) at boundaries. Shape: [N, ...]
            depth_N: The stack depth (N_crit check)
        """
        # 1. Ideal Carnot Geometric Efficiency
        # eta_ideal = 1 - (Lambda_vac / Lambda_pump)
        # Ensure lambda_pump is safely non-zero
        eta_ideal = 1.0 - (lambda_vac / (lambda_pump + 1e-8)).clamp(max=1.0)
        
        # 2. Topological Friction (Transmission coefficients)
        # tau_n = 1 - xi * |nabla epsilon_n|^2
        # We approximate nabla epsilon_n using the admr_residues magnitude
        nabla_eps_sq = torch.norm(admr_residues, dim=-1)**2
        
        # Average boundary perturbation variance
        sigma_eps_sq = nabla_eps_sq.mean()
        
        # 3. Stack Efficiency
        # eta_stack = eta_ideal * exp(-N * xi * sigma_eps_sq)
        eta_stack = eta_ideal * torch.exp(-depth_N * self.xi_shear * sigma_eps_sq)
        
        # 4. Thermodynamic Ledger
        p_waste = self.p_nuclear * (1.0 - eta_stack)
        thermal_runaway = p_waste > self.p_cool_max
        
        # 5. Critical Depth calculation (N_crit)
        # N_crit = (1 / (xi * sigma_eps_sq)) * ln(eta_ideal / (1 - (P_cool_max / P_nuclear)))
        cooling_ratio = self.p_cool_max / self.p_nuclear
        if cooling_ratio >= 1.0:
            n_crit = float('inf')
        else:
            log_arg = eta_ideal / (1.0 - cooling_ratio)
            # Safe log
            log_arg = log_arg.clamp(min=1e-6)
            n_crit = (1.0 / (self.xi_shear * sigma_eps_sq + 1e-8)) * torch.log(log_arg)
            
        return {
            "eta_ideal": eta_ideal,
            "eta_stack": eta_stack,
            "p_waste": p_waste,
            "thermal_runaway": thermal_runaway,
            "n_crit": n_crit,
            "topological_friction": sigma_eps_sq
        }
